resources:
- name: RobiNino_mvn_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/mvn-example-pipelines
    gitProvider: github_robi
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: RobiNino_mvn_example_pipelines_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: robindev
    buildName: $pipeline_name
    buildNumber: $run_number
pipelines:
- name: RobiNino_mvn_example_pipelines_pipeline
  steps:
  - name: MvnBuildStep
    type: MvnBuild
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
        JFROG_CLI_BUILD_URL: $step_url
      integrations:
      - name: robindev
      inputResources:
      - name: RobiNino_mvn_example_pipelines_gitResource
      outputResources:
      - name: RobiNino_mvn_example_pipelines_buildInfoResource
      mvnCommand: clean install
      resolverSnapshotRepo: maven-virtual
      resolverReleaseRepo: maven-virtual
    execution:
      onComplete:
      - update_commit_status RobiNino_mvn_example_pipelines_gitResource
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      outputResources:
      - name: RobiNino_mvn_example_pipelines_buildInfoResource
      inputSteps:
      - name: MvnBuildStep
      forceXrayScan: true
