updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status robiMvnExampleGit --context "$step_name"

resources:
  - name: robiMvnExampleGit
    type: GitRepo
    configuration:
      path: RobiNino/mvn-example-pipelines
      gitProvider: robi_github_vcs
      buildOn:
        pullRequestCreate: true

pipelines:
  - name: robi_mvn_example_tmp
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: robiMvnExampleGit
          integrations:
            - name: ojo
            - name: robi_eco
            - name: robi_github_vcs
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_robiMvnExampleGit_resourcePath

            # Set env
            - export CI=true
            - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`
            - export JFROG_CLI_BUILD_NAME=robi_mvn_example_tmp
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog rt c robi_eco --url $int_robi_eco_rt_url --user=$int_robi_eco_rt_user --password=$int_robi_eco_rt_password --enc-password=false
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases jfrog-dependencies --repo-resolve-snapshots jfrog-dependencies
              --server-id-deploy robi_eco --repo-deploy-releases libs-release-local --repo-deploy-snapshots libs-snapshot-local

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt mvn clean install -U -B
            - ./jfrog rt bag
            - ./jfrog rt bp

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_robiMvnExampleGit_resourcePath/target/surefire-reports/

            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home